### PR TITLE
Feature/cb vortex rollup

### PR DESCRIPTION
**Pull request by MarekWlasak**
## Description

A refactor of vortex rollup with the capability of using the code elsewhere.

[See the JEDI Documentation](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/pullrequest.html) for further information.

### Issue(s) addressed

If this does not close an existing issue, then [be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## Acceptance Criteria (Definition of Done)
Passes tests

### CODE REVIEW

**Review by odlomax — APPROVED** [review]
Nice.

**Comment by twsearle** [comment]
Out of interest, I am confused by the code coverage results for this change, does anyone understand it? It looks like the file that is causing the complaint is a test file, and the change removes some uncovered code. Also it is equivalent to the change in the file above it in the listings that causes no complaints!

**Comment by MarekWlasak** [comment]
I am confused about code coverage as well.  I have just noticed that I have missed two more copies of that test, so this afternoon I will update this PR and the ecmwf equivalent to include those.

**Comment by MarekWlasak** [comment]
@twsearle - are you o.k. with me putting this into cubed-sphere-base2?

**Review by twsearle — APPROVED** [review]
looks good to me go ahead!

**Pull request merged**
