### PR TITLE
Feature/interp wrapper2

### PR DESCRIPTION
**Pull request by MarekWlasak**
## Description
Created new branch to make github behave!

This work is for creating an interpolation/redistribution that can be used for going from one functionspace to another. 
It is primarily considering StructuredColumns and is a testbed for interpolating from StructuredColumns to CubedSphere functionspaces. (not yet tested).

The work is being done in the sandbox as a place to explore options.  There are three versions of the wrapper. Version 1 is similar to um-jedi but with the unique pointers removed.  Version 2 is slightly more generic in that it no longer has the source fields being on the Gauss grid but is limited to StructuredColumns.  

Version 3 is more generic in that it considers FunctionSpaces more generically. 

Version 3 has revealed some issues that I am unsure about, namely with using the MatchingMeshPartitioner. @wdeconinck - am I on the right path here?

It also shows that we really need the grid to be linked to the CubedSphere functionspace, like it is in StructuredColumns which I will do in another PR. 

My application works without OpenMP with mpiexec. I have not had time to work out why it crashes with OpenMP.

### Issue(s) addressed
- fixes #TBD

### CODE REVIEW

**Comment by shlyaeva** [comment]
@MarekWlasak I think we don't use JCSDA atlas fork anymore in any of the bundles (tagging @ytremolet, @rhoneyager, @climbfuji). Is this PR intended for review and merge?

**Comment by MarekWlasak** [comment]
@shlyaeva  @svahl991  - Again this is similar to the other PR.  I will close this PR as it was an exploration in the sandbox of how to do interpolation and redistribution where for the most part we are working with the up-casted base classes and downcasting only where necessary. The work here might be useful for the saber work (in particular the interpolation)

**Comment by shlyaeva** [comment]
@MarekWlasak sounds good, it's good to know! I wasn't aware of the use of jcsda-internal atlas, and got confused yesterday going through the issues in JEDI2. 

> The work here might be useful for the saber work (in particular the interpolation)

Do you think we'll need to use this fork? Or would it be included in ecmwf atlas?

**Comment by MarekWlasak** [comment]
The work there is in the sandbox of the repository. It effectively uses the methods that are in the main source and it a place to play with putting pieces together.

**Pull request closed without merging**
