### PR TITLE
Sync with ECMWF develop

### PR DESCRIPTION
**Pull request by aerorahul**
Merge `ecmwf::atlas/develop` into `jcsda::atlas/develop`

`jcsda::atlas/develop` is 8 month's stale.

### CODE REVIEW

**Comment by aerorahul** [comment]
Looks like the Travis CI builds are failing because `doxygen` and `dot` are not found.
Any idea how to fix these? 
The branch builds on my macOS with GNU compiler set.

**Comment by mmiesch** [comment]
Thanks @aerorahul  - I tested this on AWS and it seems to be fine with fv3-bundle.

**Review by mmiesch — APPROVED** [review]

**Review by ytremolet — APPROVED** [review]
I have not tested but I approve in the sense that we need to do this.
I'm not convinced we are managing branches in the best possible way when we have forks. We'll discuss that outside of this PR.

**Comment by aerorahul** [comment]
we can wait another day for @danholdaway and @benjaminmenetrier to comment before merging.

**Comment by mmiesch** [comment]
I agree that we need to discuss how we manage our forks.  Maybe we could keep our local feature branches but we should make PRs from those branches to upstream and only change our develop through synching with upstream.

Our containers have both doxygen and dot but these are not our containers.  It looks like ENABLE_DOCS is now on by default

**Comment by mmiesch** [comment]
Looks like @wdeconinck just pushed a doxygen fix

**Comment by danholdaway** [comment]
The issue with doing a straight develop to develop merge is that if it breaks some model we wont know until it's merged and develop starts failing and you have no way of triggering code build. But so long as you've tested with fv3-jedi somehow/somewhere I'm happy to merge. But would stress that Travis CI passing here is insufficient for assessing the impact of merging from upstream. At the beginning of the code sprint last month none of our models worked with ECMWF develop due to a bug not picked up by Travis.

**Comment by aerorahul** [comment]
> The issue with doing a straight develop to develop merge is that if it breaks some model we wont know until it's merged and develop starts failing and you have no way of triggering code build. But so long as you've tested with fv3-jedi somehow/somewhere I'm happy to merge. But would stress that Travis CI passing here is insufficient for assessing the impact of merging from upstream. At the beginning of the code sprint last month none of our models worked with ECMWF develop due to a bug not picked up by Travis.

The JCSDA fork is 8 months stale.  If anyone has been using the JCSDA develop, there is no guarantee things won't break.  As @ytremolet suggested, we need a way of syncing our forks timely (and possibly automatically) with upstream develop; whilst maintaining a jcsda-develop that is closely maintained with upstream.  Aren't there bots for this kind of stuff?

**Comment by wdeconinck** [comment]
I also definitely agree that you should not rely on the upstream develop branch for any model. Especially for upstream packages you would ideally rely on tagged versions. I understand that if you have features you want to develop, you can do so, but then most reliably do so from a known working tagged version. Then merge (or preferably rebase) with latest upstream develop for submitting PR upstream.
ECMWF's IFS is e.g. never using a "develop" branch. Not saying you should, but we do "synchronised (tagged) releases" of all libraries with (hopefully) thorough (unit) testing on various platforms, and use these tagged versions for IFS. Probably more tricky for you as you have multiple sites and models to deal with.

**Comment by wdeconinck** [comment]
> Our containers have both doxygen and dot but these are not our containers. It looks like ENABLE_DOCS is now on by default

Even though for Atlas the ENABLE_DOCS should be OFF by default, for eckit it is not, and in a bundle that would then change the default for ENABLE_DOCS (but not a hard requirement).

I also had some failing CI on our end, but due to a "REQUIRED" keyword in the `find_package( LATEX )` that was merged in latest PR. It is now fixed. (so please reintegrate).

**Comment by aerorahul** [comment]
> > Our containers have both doxygen and dot but these are not our containers. It looks like ENABLE_DOCS is now on by default
> 
> Even though for Atlas the ENABLE_DOCS should be OFF by default, for eckit it is not, and in a bundle that would then change the default for ENABLE_DOCS (but not a hard requirement).
> 
> I also had some failing CI on our end, but due to a "REQUIRED" keyword in the `find_package( LATEX )` that was merged in latest PR. It is now fixed. (so please reintegrate).

@wdeconinck If `ENABLE_DOCS` is turned `ON`, then isn't `LATEX` required to build the pdf documentation?   If not, then `CONDITION LATEX_FOUND` is irrelevant to build the (partial) documentation.
I suppose one can just build `doxygen` documentation.  One can wrap all different kinds of these documentation builders in their respective <PACKAGE_FOUND> if statements. 
A job for another time, perhaps!

**Comment by aerorahul** [comment]
last call! 
merging `develop-ecmwf` -> `develop` at Noon EDT.

**Comment by mmiesch** [comment]
Ok - it can be part of the mini virtual code sprint today - fixing all potential merge problems at once!

**Comment by wdeconinck** [comment]
> > > Our containers have both doxygen and dot but these are not our containers. It looks like ENABLE_DOCS is now on by default
> > 
> > 
> > Even though for Atlas the ENABLE_DOCS should be OFF by default, for eckit it is not, and in a bundle that would then change the default for ENABLE_DOCS (but not a hard requirement).
> > I also had some failing CI on our end, but due to a "REQUIRED" keyword in the `find_package( LATEX )` that was merged in latest PR. It is now fixed. (so please reintegrate).
> 
> @wdeconinck If `ENABLE_DOCS` is turned `ON`, then isn't `LATEX` required to build the pdf documentation? If not, then `CONDITION LATEX_FOUND` is irrelevant to build the (partial) documentation.
> I suppose one can just build `doxygen` documentation. One can wrap all different kinds of these documentation builders in their respective <PACKAGE_FOUND> if statements.
> A job for another time, perhaps!

I am working on another repository "atlas-docs" (not yet in Github, very much a work in progress) where I generate the documentation to be hosted here:
https://sites.ecmwf.int/docs/atlas/

In the end both the LATEX and Doxygen will then be removed from the atlas repo.

Regardless, I was also surprised, but it seems that  "ENABLE_DOCS=ON" can also be the case without it being turned on explicitly from the command-line. This is when another previous package in the bundle entered a `ecbuild_add_option( DOCS ... )` with the default "ON".
There's a `ENABLE_DOCS` CMake **option** being set to ON, for GUI purposes, which can be overridden by command-line.
In my tests ( and in the general case ) we were not explicitly setting "ENABLE_DOCS=OFF" so it was hence going into this case where "REQUIRED" was used, even if we did not explicitly turned it ON.

**Pull request merged**
